### ISSUE TITLE
Support for Diesel 2.0?

### ISSUE THREAD

**Issue by phayes** [ThouCheese/diesel-enum#2]
Hi there,

I was wondering if there are any plans to support diesel 2?   I would be willing to pay for this development if required.

**Comment by ThouCheese** [comment]
Hey, thanks for the offer. I am willing to do this for free since I need it myself too, so I whipped up a branch that you can use until Diesel 2.0 comes out: [feat/diesel-2.0](https://github.com/ThouCheese/diesel-enum/tree/feat/diesel-2.0). Let me know if you run into anything :)

**Comment by ThouCheese** [comment]
Hey there @phayes, sorry about dropping off the radar for a little there. I've pushed another change that modifies the attributes to look like this:

```rs
#[derive(Debug, Clone, Copy, PartialEq, Eq, diesel::deserialize::FromSqlRow, DbEnum)]
#[diesel(sql_type = SmallInt)]
#[diesel_enum(error_fn = CustomError::not_found)]
#[diesel_enum(error_type = CustomError)]
pub enum Status {
    /// Will be represented as 0.
    Ready,
    /// Will be represented as 1.
    Pending,
}
```

I'm no master of proc macros, so it doesn't produce the best error messages, but let me know what you think!

**Comment by zdannar** [comment]
@ThouCheese,

I just updated to the branch, things are compiling.  I will be able to report back in the near future if things are working correctly.

**Comment by peschkaj** [comment]
With Diesel now at 2.1.0, what are the odds of getting this merged into the current crate?

**Comment by ThouCheese** [comment]
@zdannar @peschkaj @phayes Support for diesel 2.0 is now on master and on crates.io! Find it at version `0.2.1`
